---
- name: Instalar 7-Zip no Windows
  hosts: windows
  gather_facts: no
  collections:
    - ansible.windows

  tasks:
    - name: Baixar o instalador do 7-Zip
      ansible.windows.win_get_url:
        url: "https://www.7-zip.org/a/7z2107-x64.exe"
        dest: "C:\\Temp\\7z2107-x64.exe"

    - name: Instalar 7-Zip
      ansible.windows.win_package:
        path: "C:\\Temp\\7z2107-x64.exe"
        arguments: "/S"
        state: present

    - name: Verificar se o 7-Zip foi instalado
      ansible.windows.win_command: "C:\\Program Files\\7-Zip\\7z.exe"
      register: result
      ignore_errors: yes

    - name: Exibir o resultado da instalação
      debug:
        var: result.stdout

